# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms, starting with 1 and 2: 1,2,3,5,8,13,...
# Considering the terms that do not exceed four million, find the sum
# of the even valued terms.

fibonaci_pair = [1,2]
sum = 2
while fibonaci_pair[1] < 4000000:
    potential_add = fibonaci_pair[0] + fibonaci_pair[1] #Selfnote
    if potential_add % 2 == 0:
        sum += potential_add
        fibonaci_pair[0] = fibonaci_pair[1]
        fibonaci_pair[1] = potential_add
    else:
        fibonaci_pair[0] = fibonaci_pair[1]
        fibonaci_pair[1] = potential_add

print(sum)

# Selfnote: the constants defined before the loop do not chain react
# to modifications imposed on other constants by the procedures inside a loop.

